[theme]
primaryColor         = "#f6ba3b"
backgroundColor      = "#ffffff"
secondaryBackgroundColor = "#f4f6f8"
textColor            = "#1a2a35"
font                 = "sans serif"

[server]
headless            = true
enableCORS          = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
